USE master
GO

CREATE DATABASE DATN64
GO

USE DATN64
GO

CREATE TABLE DanhMuc
(
MaDanhMuc INT IDENTITY(1,1) PRIMARY KEY,
TenDanhMuc NVARCHAR(100) NOT NULL,
MoTa NVARCHAR(500)
)
GO

CREATE TABLE ThuongHieu
(
MaThuongHieu INT IDENTITY(1,1) PRIMARY KEY,
TenThuongHieu NVARCHAR(100) NOT NULL,
MoTa NVARCHAR(500)
)
GO

CREATE TABLE NhaCungCap
(
MaNCC INT IDENTITY(1,1) PRIMARY KEY,
TenNCC NVARCHAR(200) NOT NULL,
SoDienThoai VARCHAR(20),
Email VARCHAR(100),
DiaChi NVARCHAR(255)
)
GO

CREATE TABLE NhanVien
(
MaNhanVien INT IDENTITY(1,1) PRIMARY KEY,
HoTen NVARCHAR(150) NOT NULL,
Email VARCHAR(100),
SoDienThoai VARCHAR(20),
MatKhau VARCHAR(255) NOT NULL,
VaiTro NVARCHAR(50),
TrangThai NVARCHAR(50)
)
GO

CREATE TABLE KhachHang
(
MaKhachHang INT IDENTITY(1,1) PRIMARY KEY,
HoTen NVARCHAR(150) NOT NULL,
SoDienThoai VARCHAR(20),
Email VARCHAR(100),
DiaChi NVARCHAR(255),
DiemTichLuy INT DEFAULT 0
)
GO

CREATE TABLE SanPham
(
MaSanPham INT IDENTITY(1,1) PRIMARY KEY,
TenSanPham NVARCHAR(255) NOT NULL,


MaDanhMuc INT NOT NULL,
MaThuongHieu INT NOT NULL,
MaNCC INT NOT NULL,

GiaNhap DECIMAL(18,2) NOT NULL,
GiaBan DECIMAL(18,2) NOT NULL,
SoLuongTon INT DEFAULT 0,

MoTa NVARCHAR(MAX),
HinhAnh NVARCHAR(500),
TrangThai NVARCHAR(50),

FOREIGN KEY (MaDanhMuc) REFERENCES DanhMuc(MaDanhMuc),
FOREIGN KEY (MaThuongHieu) REFERENCES ThuongHieu(MaThuongHieu),
FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC)

)
GO

CREATE TABLE DonHang
(
MaDonHang INT IDENTITY(1,1) PRIMARY KEY,
MaKhachHang INT NOT NULL,
MaNhanVien INT NOT NULL,

NgayDat DATETIME DEFAULT GETDATE(),
TongTien DECIMAL(18,2),

TrangThai NVARCHAR(50),
PhuongThucThanhToan NVARCHAR(50),

FOREIGN KEY (MaKhachHang) REFERENCES KhachHang(MaKhachHang),
FOREIGN KEY (MaNhanVien) REFERENCES NhanVien(MaNhanVien)

)
GO

CREATE TABLE ChiTietDonHang
(
MaChiTiet INT IDENTITY(1,1) PRIMARY KEY,
MaDonHang INT NOT NULL,
MaSanPham INT NOT NULL,


SoLuong INT NOT NULL,
DonGia DECIMAL(18,2) NOT NULL,

FOREIGN KEY (MaDonHang) REFERENCES DonHang(MaDonHang),
FOREIGN KEY (MaSanPham) REFERENCES SanPham(MaSanPham)

)
GO

CREATE TABLE PhieuNhap
(
MaPhieuNhap INT IDENTITY(1,1) PRIMARY KEY,
MaNCC INT NOT NULL,
MaNhanVien INT NOT NULL,

NgayNhap DATETIME DEFAULT GETDATE(),

FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC),
FOREIGN KEY (MaNhanVien) REFERENCES NhanVien(MaNhanVien)

)
GO

CREATE TABLE ChiTietPhieuNhap
(
MaChiTiet INT IDENTITY(1,1) PRIMARY KEY,
MaPhieuNhap INT NOT NULL,
MaSanPham INT NOT NULL,

SoLuong INT NOT NULL,
GiaNhap DECIMAL(18,2) NOT NULL,

FOREIGN KEY (MaPhieuNhap) REFERENCES PhieuNhap(MaPhieuNhap),
FOREIGN KEY (MaSanPham) REFERENCES SanPham(MaSanPham)


)
GO

CREATE TABLE Voucher
(
MaVoucher INT IDENTITY(1,1) PRIMARY KEY,
MaCode VARCHAR(50) UNIQUE,
GiaTri DECIMAL(18,2),
SoLuong INT,
NgayBatDau DATETIME,
NgayKetThuc DATETIME
)
GO

CREATE TABLE DonHang_Voucher
(
MaDonHang INT NOT NULL,
MaVoucher INT NOT NULL,

PRIMARY KEY (MaDonHang, MaVoucher),

FOREIGN KEY (MaDonHang) REFERENCES DonHang(MaDonHang),
FOREIGN KEY (MaVoucher) REFERENCES Voucher(MaVoucher)

)
GO
